language: csharp
os:
- osx
osx_image: xcode9.2
rvm:
- 2.2
jobs:
  include:
 - stage: deploy
   script: 
    ./Scripts/build.sh"
    mono: none
    install:
    - "./Scripts/Install/unity.sh"
env:
  global:
  - BUILD_VERSION=$( date +%Y.%V )

before_install:
- chmod +x ./Scripts/Install/unity.sh
- chmod +x ./Scripts/build.sh